### ISSUE TITLE
can't find module 

### ISSUE THREAD

**Issue by continuata** [jankopriva/react-infinite-list#2]
I'm using `npm install react-infinite-list` which downloads and installs the module correctly into my node_modules folder.

But when I try to `require('react-infinite-list')` it throws an error, claiming that it can't be found.

If I require the file directly from the path using `require('../node_modules/react-infinite-list/dist/infinite_list.js';` it seems to work fine.
Any ideas?

**Comment by jankopriva** [comment]
Hi, I forgot to add entry point to the package.json. Will fix it ASAP, thanks for reporting.

**Comment by continuata** [comment]
thanks

**Comment by jankopriva** [comment]
Ok version 0.0.4 published. Please, update you package.json and try again.

**Comment by continuata** [comment]
Error: Parsing file /home/codio/workspace/node_modules/react-infinite-list/src/infinite_list.js: Unexpected token (8:12)

**Comment by jankopriva** [comment]
Are you using webpack? If so you need to configure it to understand jsx in .js files. For example:

  module.exports = {
    entry: {
        app: ['webpack/hot/dev-server', './main.jsx']
    },
    output: {
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.jsx$/, loader: 'jsx-loader' },
            { test: /\.js$/, loader: 'jsx-loader' },
            { test: /\.css$/, loader: "style!css" }
        ]
    },
    resolve: {
        extensions: ['', '.js', '.jsx']
    }
};

**Comment by continuata** [comment]
I'm using `browserify -t reactify index.js -o bundle.js`

**Comment by jankopriva** [comment]
It looks like reactify does not translate jsx syntax from other modules than the one specified on the command line. See https://github.com/andreypopp/reactify/issues/20 for more details. I would recommend either setup gulp task or switch to webpack, which is more advanced and painless.

**Comment by continuata** [comment]
will take a look at webpack then ... thanks again
